language: node_js
node_js:
  - "lts/*"
dist: trusty
addons:
  apt:
    update: true

install:
  # Install pandoc.
  # - wget https://github.com/jgm/pandoc/releases/download/2.1/pandoc-2.1-1-amd64.deb
  # - sudo dpkg -i ./pandoc-2.1-1-amd64.deb
  # - sudo apt install -f
  # - pandoc -v

before_script:
  # Install hexo & dependencies.
  - npm install

script:
  # Generate static files.
  - hexo clean
  - hexo generate

  # Configure git for deploying.
  - git config --global user.name 'codgician'
  - git config --global user.email 'codgician@users.noreply.github.com'
  - sed -i'' "s~https://github.com/codgician/blog-legacy.git~https://${GITHUB_TOKEN}@github.com/codgician/blog-legacy.git~" _config.yml

  # Deploy blog.
  - hexo deploy --debug
  
