language: node_js
node_js:
  - "node"

dist: trusty

install:
  # Install pandoc.
  # - wget https://github.com/jgm/pandoc/releases/download/2.1/pandoc-2.1-1-amd64.deb
  # - sudo dpkg -i ./pandoc-2.1-1-amd64.deb
  # - sudo apt install -f
  # - pandoc -v

before_script:
  # Install hexo & dependencies.
  - yarn install

script:
  # Generate static files.
  - hexo clean --debug
  - hexo generate --debug

  # Configure git for deploying.
  - git config --global user.name 'codgician'
  - git config --global user.email 'codgician@users.noreply.github.com'
  - sed -i'' "s~https://github.com/codgician/codgician.github.io.git~https://${GITHUB_TOKEN}@github.com/codgician/codgician.github.io.git~" _config.yml

  # Deploy blog.
  - hexo deploy --debug
  
